version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./SupplyChainWeb3Client/src:/app/src
      - ./SupplyChainWeb3Client/public:/app/public
    ports:
      - "3000:3000"
